server:
  port: 23333
  servlet:
    context-path: /nekoverse

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nekoverse
    username: NEKO
    password: "DB-MYSQL-C101"
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  devtools:
    # 热更新
    restart:
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  configuration:
    # 自动驼峰映射
    map-underscore-to-camel-case: true

